name: Mostrar autor del último commit
description: Imprime el nombre del autor del último commit en los logs

runs:
  using: "composite"
  steps:
    - name: Obtener autor del último commit
      shell: bash
      run: |
        AUTHOR_NAME=$(git log -1 --pretty=format:'%an') 
        echo "El autor del último commit es: $AUTHOR_NAME de la empresa Stemdo"
