name: Crear archivo de texto
description: Crea un archivo de texto con un mensaje personalizado

inputs:
  filename:
    description: Nombre del archivo a crear
    required: true
  message:
    description: Contenido del archivo
    required: true

runs:
  using: "composite"
  steps:
    - name: Crear archivo
      shell: bash
      run: |
        echo "Creando archivo '${{ inputs.filename }}' con el mensaje:"
        echo "${{ inputs.message }}"
        echo "${{ inputs.message }}" > "${{ inputs.filename }}"
