name: Subir y Descargar Archivo como Artefacto

on:
  push:
    branches:
      - feature

jobs:
  subir-archivo:
    runs-on: labs-runner
    steps:
      - name: Verificar archivo existente
        run: |
          if [ -f "saludo.txt" ]; then
            echo "El archivo existe, continuando con la carga..."
          else
            echo "El archivo no existe."
            exit 1
          fi

      - name: Subir archivo como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-existente
          path: saludo.txt

  mostrar-contenido:
    runs-on: labs-runner
    needs: subir-archivo
    steps:
      - name: Descargar el archivo artefacto
        uses: actions/download-artifact@v4
        with:
          name: archivo-existente

      - name: Mostrar el contenido del archivo
        run: |
          cat saludo.txt
