name: Informaci贸n del Runner

on:
  workflow_dispatch:

jobs:
  mostrar-infomaci贸n-runner:
    runs-on: labs-runner
    permissions: write-all

    steps:
      - name: Mostrar nombre del sistema operativo
        run: echo "Sistema operativo $(uname -s)"

      - name: Mostrar arquitectura del sistema
        run: echo "Arquitectura $(uname -m)"

      - name: Mostrar informaci贸n completa del sistema
        run: uname -a

      - name: Mostrar espacio en disco disponible
        run: df -h

      - name: Mostrar informaci贸n del runner (env)
        run: env | grep RUNNER
