name: Confirmación Manual

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Confirmar true o false'
        required: true
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  ejecutar-accion:
    runs-on: labs-runner
    steps:
      - name: Imprimir mensaje basado en confirmación
        run: |
          if [ "${{ github.event.inputs.confirm }}" == "true" ]; then
            echo "La confirmación es positiva: Acción ejecutada."
          else
            echo "La confirmación es negativa: Acción cancelada."
          fi
