name: Dispatch 2

on:
  workflow_dispatch:  # Nos permite ejecutar el workflow manualmente desde Github
    inputs:
      environment:
        description: 'Selecciona el entorno'
        required: true
        default: staging   
        type: choice
        options:
          - production
          - staging

jobs:
  print-environment:
    runs-on: labs-runner
    steps:
      - name: Mostrar entorno seleccionado
        run: echo "Entorno seleccionado: ${{ github.event.inputs.environment }}" # Mostramos el valor