name: Tareas en Workflow

on:
  workflow_dispatch:

jobs:
  run-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: 
        uses: actions/checkout@v3

      - name: Fecha
        run: date

      - name: Crear archivo de texto
        run: touch pruebaJobs1.txt

      - name: Mostrar archivos
        run: ls 

      - name: Configurar Git
        run: |
          git config user.name "adiazstemdo"
          git config user.email "adiazstemdo@io.com"

      - name: Añadir archivos y pushear
        run: |
          git add .
          git commit -m "Auto-commit desde workflow"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
