name: Build y Deploy Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: labs-runner
    steps:
      - name: Comprobar código
        uses: actions/checkout@v3

      - name: Build step (simulado)
        run: |
          echo "Ejecutando proceso de build..."
          # exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy step
        run: echo "El job deploy funciona."
