name: Crear y Mover Archivo en el Mismo Workflow

on:
  push:
    branches:
      - feature

jobs:
  crear-archivo:
    runs-on: ubuntu-latest
    steps:
      - name: Crear archivo test.txt
        run: echo "Este es un archivo de prueba" > test.txt   # Aquí estoy rediriegiendo la salida de echo a un archivo llamado test.txt

      - name: Subir archivo como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-de-prueba
          path: test.txt

  mover-archivo:
    runs-on: ubuntu-latest
    needs: crear-archivo
    steps:
      - name: Descargar el archivo
        uses: actions/download-artifact@v4
        with:
          name: archivo-de-prueba

      - name: Mover el archivo a otro directorio
        run: |
          mkdir destino                               
          mv test.txt destino/                        
          echo "Contenido de 'destino/'"
          ls destino/                         