name: Trigger Deploy

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  trigger-deploy:
    runs-on: labs-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine deployment environment
        id: environment
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "Desplegando a production"
            echo "environment=production" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            echo "Desplegando a development"
            echo "environment=development" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == refs/heads/release/* ]]; then
            echo "Desplegando a staging"
            echo "environment=staging" >> $GITHUB_ENV
          fi

      - name: Llamando a workflow
        uses: ./.github/workflows/main.reusable3.yml
        with:
          environment: ${{ env.environment }}
