name: Validar y Ejecutar si es feature/

on:
  workflow_call:    # Llamamos al workflow para que solo se ejecute si le llama otro workflow
    inputs:
      mensaje:
        required: true
        type: string

jobs:
  validar-rama:
    runs-on: labs-runner
    outputs:
      es_feature: ${{ steps.verificar.outputs.es_feature }}
    steps:
      - name: Verificar si la rama es "feature*"
        id: verificar
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Nombre de la rama: $BRANCH_NAME"
          
          if [[ "$BRANCH_NAME" == feature* ]]; then
            echo "es_feature=true" >> $GITHUB_OUTPUT
          else
            echo "es_feature=false" >> $GITHUB_OUTPUT
          fi

  ejecutar-si-es-feature:
    needs: validar-rama
    if: needs.validar-rama.outputs.es_feature == 'true'
    runs-on: labs-runner
    steps:
      - name: Ejecutando tarea principal
        run: echo "Esta rama es una feature. Ejecutando acción principal..."
