name: Variables 4. Validación de json y condicional 

on:
  push:       # Se ejecuta cada vez que se hace push desde la rama main o develop
    branches:
      - main
      - feature

jobs:
  validar-config:
    name: Version config.json
    runs-on: labs-runner
    outputs:
      app_version: ${{ steps.get_version.outputs.app_version }}

    steps:
      - name: Checkout code       # clona el código del repositorio para que el workflow pueda acceder a los archivos (como config.json).
        uses: actions/checkout@v3

      - name: comprobar si existe el archivo config.json
        run: |
          if [ ! -f config.json ]; then
            echo "config.json no existe"
            exit 1
          fi

      - name: Validar archivo .json
        run: |
          jq . config.json > /dev/null || { echo "Invalid JSON"; exit 1; }  

      - name: Version
        id: get_version
        run: |
          VERSION=$(jq -r '.version' config.json)    
          echo "App version: $VERSION"
          echo "app_version=$VERSION" >> $GITHUB_OUTPUT    

  deploy:
    name: Condicional if
    needs: Validar-config    # Este trabajo depende del trabajo validar-config. No se ejecutará hasta que validar-config haya terminado con éxito.
    runs-on: labs-runner

    steps:
      - name: Despliegue a Producción
        if: github.ref == 'refs/heads/main'    # Se ejecuta si la rama es main
        run: echo "Desplegar version ${{ needs.validate-config.outputs.app_version }} a PRODUCCIÓN"

      - name: Despliegue a Desarrollo
        if: github.ref == 'refs/heads/feature'    # Se ejecuta si la rama es feature
        run: echo "Desplegar version ${{ needs.validate-config.outputs.app_version }} a FEATURE"
