name: Workflow con Secreto

on:
  push:
    branches:
      - '**'

jobs:
  variable-secreto:
    runs-on: labs-runner

    steps:
      - name: Guardar secreto en variables
        env:
          secreto: ${{ secrets.MISECRETO }}
        run: |
          echo "El secreto es: $secreto"
